---
language: python
services: docker

branches:
  only:
    - master
    - devel

env:
  global:
    - ROLE_NAME: sonobouy
  matrix:
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604

install:
  # Install test dependencies.
  - pip install molecule==2.20.1 ansible==2.7.0 testinfra==1.19.0 docker

script:
  # Run tests.
  - molecule test

after_sucess:
  - codedov

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
