---
language: python
services: docker

env:
  global:
    - ROLE_NAME: sonobouy
  matrix:
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - pwd
  - cd ansible-$ROLE_NAME-ubuntu

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/