---
language: python
services: 
  - docker

branches:
  only:
    - master
    - devel

env:
  global:
    - ROLE_NAME: sonobouy
  matrix:
    - MOLECULE_DISTRO: ubuntu:1804
    - MOLECULE_DISTRO: ubuntu:1604

install:
  # Install test dependencies.
  - pip install molecule==2.20.1 ansible==2.7.0 testinfra==1.19.0 docker codecov pytest-cov

script:
  # Run tests.
  - molecule test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    on_success: never
    on_failure: always
