---
language: python
python: 3.6
services:
  - docker

branches:
  only:
    - master
    - devel

env:
  global:
    - ROLE_NAME: sonobouy
  matrix:
    - MOLECULE_DISTRO: ubuntu:20.04
    - MOLECULE_DISTRO: ubuntu:19.10
    - MOLECULE_DISTRO: ubuntu:18.04
    - MOLECULE_DISTRO: ubuntu:16.04
    - MOLECULE_DISTRO: centos:7

install:
  # Install test dependencies.
  - pip install -r requirements.txt

script:
  # Run tests.
  - molecule test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    on_success: never
    on_failure: always
