---
# tasks file for ansible-sonobuoy-ubuntu

- name: Include tasks for OS specific
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"

- name: Verify if directory already exists
  stat:
    path: '{{ sonobuoy_download_path }}'
  register: dirs_stat

- name: Create download directory
  become: true
  become_user: root
  file:
    path: '{{ sonobuoy_download_path }}'
    state: directory
    mode: '0755'
    recurse: true
  when:
    - not dirs_stat.stat.exists

- name: download sonobuoy
  become: true
  become_user: root
  get_url:
    url: '{{ sonobuoy_url }}'
    dest: '{{ sonobuoy_download_path }}'
    checksum: '{{ sonobuoy_checksum }}'
    mode: '0755'

- name: extract sonobuoy
  become: true
  become_user: root
  unarchive:
    src: "{{ sonobuoy_download_path }}/{{ sonobuoy_bin }}_{{ sonobuoy_version }}_{{ sonobuoy_os }}_{{ sonobuoy_platform }}.tar.gz"
    dest: "{{ sonobuoy_download_path }}"
    remote_src: true

- name: link sonobuoy
  become: true
  become_user: root
  file:
    src: '{{ sonobuoy_download_dir }}/{{ sonobuoy_bin }}-{{ sonobuoy_version }}/{{ sonobuoy_bin }}'
    dest: '{{ sonobuoy_install_dir }}/{{ sonobuoy_bin }}'
    state: link
