name: Python application

on: [push]

env:
  global:
    - ROLE_NAME: sonobouy
  matrix:
    - MOLECULE_DISTRO: ubuntu:20.04
    - MOLECULE_DISTRO: ubuntu:19.10
    - MOLECULE_DISTRO: ubuntu:18.04
    - MOLECULE_DISTRO: ubuntu:16.04
    - MOLECULE_DISTRO: centos:7
    - MOLECULE_DISTRO: centos:6

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Molecule test
      run: |
        molecule test

