name: Molecule Test

on:
  pull_request:
    branches:
    - master
    - devel

  push:
    branches:
    - master
    - devel

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
          distro:
          - "ubuntu:20.04"
          - "ubuntu:19.10"
          - "ubuntu:18.04"
          - "ubuntu:16.04"
          - "centos:7"
          - "centos:6"

    env:
      MOLECULE_DISTRO: ${{ matrix.distro }}  

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Molecule test
      run: |
        molecule test
